### PR TITLE
Add Icon State Push Button

### PR DESCRIPTION
**Pull request by Bjoern3003**
Add Timestamp Widget for Value

### CODE REVIEW

**Comment by Bjoern3003** [comment]
Ahh ich sehe gerade in #172 gibt es einen solch ähnlichen Pull Request bereits...

**Comment by GermanBluefox** [comment]
Thank you for you PR.
Can you give me your email? I will send you a license agreement.
The license requires it. 

info@iobroker.net

**Comment by Bjoern3003** [comment]
Hi, a license agreement for what?

**Comment by GermanBluefox** [comment]
> Hi, a license agreement for what?

iobroker.vis has CC-BY NC. That means "free for non-commercial use". If I will try to use it in commercial way, you, as contributor has rights for your code. With license agreement you will accept, that you give all rights for your contributed code to me.

**Comment by Bjoern3003** [comment]
New Pull Request with new Add Icon State Push Button

**Comment by Bjoern3003** [comment]
Push: Has not yet been included in the adapter.

**Pull request merged**
