### PR TITLE
added array operator to bindings

### PR DESCRIPTION
**Pull request by soef**
e.g.: {id.ack;array(ack is false,ack is true)}

### CODE REVIEW

**Comment by GermanBluefox** [comment]
How to use it? Readme.md?

**Comment by soef** [comment]
Ok, ich have removed the wrong komma and added a line in the readme.

**Review by GermanBluefox — COMMENTED** [review]
Sorry. I still do not understand how to use it. :(

**Comment by soef** [comment]
In each text field you can use {} evauate an Expression. Here a smal example
The value of ack is {idOfAState.ack;array("not acknowledged","acknowledged")}

**Comment by GermanBluefox** [comment]
Thank you

**Comment by Apollon77** [comment]
@soef maybe use this example in readme ... should be better understandable :-)

**Pull request merged**
