### PR TITLE
Update words.js

### PR DESCRIPTION
**Pull request by Fiiti**
Some german Words and sentenance optimized.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you for the translations.
Because the vis has CC-NC License I need the License Agreement from you, that I can send you.

So the changes are not huge I can just take you suggestions without merge. (and without License Agreement). What is better for you?

**Comment by Fiiti** [comment]
I would be happy to understand, how I can give you the Agreement. Is there a Button?
Of course you get the Agreement.
So sorry for the circumstances.
If you could it explain to me, it would be very nice. In Future i could faster and productiver to you. Maybe. :-) 
Otherwise - your time has to be safed - feel free to copy an paste them.

**Comment by GermanBluefox** [comment]
There is no button for that. I will send you the document per email. You should sign it, scan and send me back (or via post)..
Rather long story.

>So sorry for the circumstances.

I am guilty in that. But it is easier for me later. :) 

>Otherwise - your time has to be safed - feel free to copy an paste them.

Will do. Thank you.

**Comment by Fiiti** [comment]
Okay.  But send it me also.
so I can sign it and send to you back for future additions.
galseq@googlemail.com
or per pn in iobroker forum. Fitti.

Am I right that I can close this pull. 
I am new with this

**Comment by GermanBluefox** [comment]
No. Let it opened.

20 янв. 2018 г. 9:27 пользователь "Fiiti" <notifications@github.com>
написал:

**Comment by GermanBluefox** [comment]
I merged the changes. Thank you one more time.

**Pull request closed without merging**
