### PR TITLE
Support for iobroker.<name> widgets

### PR DESCRIPTION
**Pull request by angelnu**
Patch that allows widget from iobroker.chromecast to be copied by vis.

See [forum](http://forum.iobroker.net/viewtopic.php?f=24&t=2005).

### CODE REVIEW

**Comment by angelnu** [comment]
Hi Bluefox,
maybe you did not see this pull-request and the one at https://github.com/ioBroker/ioBroker.js-controller/pull/111.
After they are integrated then iobroker.chromecast should be ready for "production".

**Comment by GermanBluefox** [comment]
I have seen your changes. Thank you. Just want to find time to analyse your changes. I was out of PC last weekend till today.

**Comment by GermanBluefox** [comment]
Is it ok if I will merge manually the changes? We are not yet conclusive about license and I dont have finished license agreement?

**Comment by angelnu** [comment]
Sure! It is really a small change.

**Pull request closed without merging**
